# Generated by Django 5.0 on 2023-12-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_details', to='student.student'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='student.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.student'),
        ),
    ]
